name: 라이벌 업데이트
description: solved.ac 라이벌 페이지 내용을 붙여넣어 라이벌 목록을 갱신합니다.
title: "[rivals] 라이벌 목록 업데이트 요청"
labels:
  - update-rivals
body:
  - type: markdown
    attributes:
      value: |
        solved.ac 라이벌 페이지에서 복사한 내용을 아래에 붙여넣어 주세요.
        JSON/HTML/텍스트 모두 가능합니다.

  - type: textarea
    id: raw_input
    attributes:
      label: 붙여넣기 내용
      description: solved.ac 라이벌 페이지에서 복사한 원문을 그대로 붙여넣어 주세요.
      placeholder: 여기 붙여넣기
    validations:
      required: true

  - type: checkboxes
    id: privacy
    attributes:
      label: 확인 사항
      options:
        - label: 쿠키/토큰 같은 민감 정보는 포함하지 않았습니다.
          required: true
